teams:
  - name: cool-cats
    maintainers:
      - ryjones
    members:
      - Skipias
      - VitaliiYakovlev
      - davidwboswell
      - hartm
      - hendrikebbers
      - hyperledger-bot
      - jordanconway
      - jwagantall
      - nathanklick
      - rbarker-dev
      - tkuhrt
repositories:
  - name: FILTER
    teams:
      cool-cats: maintain
    visibility: private
  - name: clo
    teams:
      cool-cats: maintain
    visibility: public
  - name: ghe
    teams:
      cool-cats: write
    visibility: private
  - name: pgsql-ghel
    teams:
      cool-cats: write
    visibility: private
